Add bug reports
flyve-mdm/flyve-mdm-deeplink pull request #8
Opened 2017-10-02 21:57 UTC by Gianfranco97

Hi @ajsb85 

In this PR add bug reports using Bugsnag.

2017-10-05 00:47 UTC, ajsb85 requested changes

2017-10-05 00:47 UTC, ajsb85 commented on index.html
> +            src="//d2wy8f7a9ursnm.cloudfront.net/bugsnag-3.min.js"
Could you use this file stored in the same branch?

2017-10-05 00:47 UTC, ajsb85 commented on index.html
> +            src="//d2wy8f7a9ursnm.cloudfront.net/bugsnag-3.min.js"
@Gianfranco97 Any update about this request?

2017-10-05 00:47 UTC, ajsb85 commented
Hi, @Gianfranco97 

Could you use the library for bugsnag stored in our repo instead cloudfront?

Thanks.

2017-10-06 15:06 UTC, Gianfranco97 commented
@ajsb85 I have already made the requested changes, could you please review it?

2017-10-06 15:46 UTC, ajsb85 approved these changes
Reviewed

2017-10-06 15:46 UTC, merged